const PRODUCTS = {

    LOAD: "PRODUCTS_LOAD",
    LOAD_SUCCESS: "PRODUCTS_LOAD_SUCCESS",
    LOAD_FAILURE: "PRODUCTS_LOAD_FAILURE",
    GET_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
    GET_BY_DEPT: "GET_PRODUCTS_BY_DEPARTMENT",



}

const CART = {
    ADD_ITEM: "ADD_ITEM",
    ADD_ITEM_DB: "ADD_ITEM_DB",
   
    REMOVE_ITEM: "REMOVE_ITEM",
    REMOVE_ITEM_SUCESS: "REMOVE_ITEM_SUCESS",
   
    UPDATE_ITEM: "UPDATE_ITEM",
   
    
    GET_TOTAL_AMOUNT: "GET_TOTAL_AMOUNT",
    GET_ITEMS: "GET_ITEMS",
    
    SET_ITEMS: "SET_ITEMS",

    GET_CART_ID: "GET_CART_ID",
    SET_CART_ID: "SET_CART_ID",
    SET_ERROR: "SET_ERROR",
    SET_NOTIFICATION: "SET_NOTIFICATION",
    DELETE_CART: "DELETE_CART"
    
    

}

const AUTH = {
    LOGIN: "LOGIN_USER",
    REGISTER: "REGISTER_USER",
    SET_USER: "SET_USER",
    FAIL: "AUTH_FAIL",
    LOGOUT: "LOGOUT_USER"
}

const CHECKOUT = {
    CREATE: "CREATE_ORDER",
    UPDATE: "UPDATE_CUSTOMER_ADDRESS",
    GET_ORDER: "GET_ORDER",
    GET_ORDER_DETAILS: 'GET_ORDER_DETAILS',

}
export {PRODUCTS, CART, AUTH, CHECKOUT}